generated
pluralVariablesMap
	^ Dictionary new
		at: 'test' put: 'tests';
		at: 'commaToken' put: 'commaTokens';
		at: 'equalToken' put: 'equalTokens';
		at: 'yieldToken' put: 'yieldTokens';
		at: 'arguments' put: 'argumentses';
		at: 'trailer' put: 'trailers';
		at: 'one' put: 'ones';
		at: 'orToken' put: 'orTokens';
		at: 'two' put: 'twos';
		at: 'name' put: 'names';
		at: 'asToken' put: 'asTokens';
		at: 'rename' put: 'renames';
		at: 'nameToken' put: 'nameTokens';
		at: 'ifToken' put: 'ifTokens';
		at: 'if' put: 'ifs';
		at: 'elseToken' put: 'elseTokens';
		at: 'else' put: 'elses';
		at: 'lambdaToken' put: 'lambdaTokens';
		at: 'colonToken' put: 'colonTokens';
		at: 'body' put: 'bodies';
		yourself