generated-reduction actions
reduceActionForTypes8: nodes
	| result |
	result := Array new: 41.
	result at: 1 put: (OrderedCollection new: 2).
	result at: 2 put: (OrderedCollection new: 2).
	result at: 3 put: (OrderedCollection new: 2).
	result at: 4 put: (OrderedCollection new: 2).
	result at: 5 put: (OrderedCollection new: 2).
	result at: 6 put: (OrderedCollection new: 2).
	result at: 7 put: (OrderedCollection new: 2).
	result at: 8 put: (OrderedCollection new: 2).
	result at: 9 put: (OrderedCollection new: 2).
	result at: 10 put: (OrderedCollection new: 2).
	result at: 11 put: (OrderedCollection new: 2).
	result at: 12 put: (OrderedCollection new: 2).
	result at: 13 put: (OrderedCollection new: 2).
	result at: 14 put: (OrderedCollection new: 2).
	result at: 15 put: (OrderedCollection new: 2).
	result at: 16 put: (OrderedCollection new: 2).
	result at: 17 put: (OrderedCollection new: 2).
	result at: 18 put: (OrderedCollection new: 2).
	result at: 19 put: (OrderedCollection new: 2).
	result at: 20 put: (OrderedCollection new: 2).
	result at: 21 put: (OrderedCollection new: 2).
	result at: 22 put: (OrderedCollection new: 2).
	result at: 23 put: (OrderedCollection new: 2).
	result at: 24 put: (OrderedCollection new: 2).
	result at: 25 put: (OrderedCollection new: 2).
	result at: 26 put: (OrderedCollection new: 2).
	result at: 27 put: (OrderedCollection new: 2).
	result at: 28 put: (OrderedCollection new: 2).
	result at: 29 put: (OrderedCollection new: 2).
	result at: 30 put: (OrderedCollection new: 2).
	result at: 31 put: (OrderedCollection new: 2).
	result at: 32 put: (OrderedCollection new: 2).
	result at: 33 put: (OrderedCollection new: 2).
	result at: 34 put: (OrderedCollection new: 2).
	result at: 35 put: (OrderedCollection new: 2).
	result at: 36 put: (OrderedCollection new: 2).
	result at: 37 put: (OrderedCollection new: 2).
	result at: 38 put: (OrderedCollection new: 2).
	result at: 39 put: (OrderedCollection new: 2).
	result at: 40 put: (OrderedCollection new: 2).
	result at: 41 put: (OrderedCollection new: 2).
	self add: (nodes at: 1) to: (result at: 15).
	self add: (nodes at: 2) to: (result at: 10).
	self add: (nodes at: 3) to: (result at: 16).
	self addAll: ((nodes at: 4) at: 1) to: (result at: 1).
	self addAll: ((nodes at: 4) at: 2) to: (result at: 2).
	self addAll: ((nodes at: 4) at: 3) to: (result at: 3).
	self addAll: ((nodes at: 4) at: 4) to: (result at: 4).
	self addAll: ((nodes at: 4) at: 5) to: (result at: 5).
	self addAll: ((nodes at: 4) at: 6) to: (result at: 6).
	self addAll: ((nodes at: 4) at: 7) to: (result at: 7).
	self addAll: ((nodes at: 4) at: 8) to: (result at: 8).
	self addAll: ((nodes at: 4) at: 9) to: (result at: 9).
	self addAll: ((nodes at: 4) at: 10) to: (result at: 10).
	self addAll: ((nodes at: 4) at: 11) to: (result at: 11).
	self addAll: ((nodes at: 4) at: 12) to: (result at: 12).
	self addAll: ((nodes at: 4) at: 13) to: (result at: 13).
	self addAll: ((nodes at: 4) at: 14) to: (result at: 14).
	self addAll: ((nodes at: 4) at: 15) to: (result at: 15).
	self addAll: ((nodes at: 4) at: 16) to: (result at: 16).
	self addAll: ((nodes at: 4) at: 17) to: (result at: 17).
	self addAll: ((nodes at: 4) at: 18) to: (result at: 18).
	self addAll: ((nodes at: 4) at: 19) to: (result at: 19).
	self addAll: ((nodes at: 4) at: 20) to: (result at: 20).
	self addAll: ((nodes at: 4) at: 21) to: (result at: 21).
	self addAll: ((nodes at: 4) at: 22) to: (result at: 22).
	self addAll: ((nodes at: 4) at: 23) to: (result at: 23).
	self addAll: ((nodes at: 4) at: 24) to: (result at: 24).
	self addAll: ((nodes at: 4) at: 25) to: (result at: 25).
	self addAll: ((nodes at: 4) at: 26) to: (result at: 26).
	self addAll: ((nodes at: 4) at: 27) to: (result at: 27).
	self addAll: ((nodes at: 4) at: 28) to: (result at: 28).
	self addAll: ((nodes at: 4) at: 29) to: (result at: 29).
	self addAll: ((nodes at: 4) at: 30) to: (result at: 30).
	self addAll: ((nodes at: 4) at: 31) to: (result at: 31).
	self addAll: ((nodes at: 4) at: 32) to: (result at: 32).
	self addAll: ((nodes at: 4) at: 33) to: (result at: 33).
	self addAll: ((nodes at: 4) at: 34) to: (result at: 34).
	self addAll: ((nodes at: 4) at: 35) to: (result at: 35).
	self addAll: ((nodes at: 4) at: 36) to: (result at: 36).
	self addAll: ((nodes at: 4) at: 37) to: (result at: 37).
	self addAll: ((nodes at: 4) at: 38) to: (result at: 38).
	self addAll: ((nodes at: 4) at: 39) to: (result at: 39).
	self addAll: ((nodes at: 4) at: 40) to: (result at: 40).
	self addAll: ((nodes at: 4) at: 41) to: (result at: 41).
	self add: (nodes at: 5) to: (result at: 17).
	^ result