generated-initialize-release
initialize
	super initialize.
	colonTokens := OrderedCollection new: 2.
	suites := OrderedCollection new: 2.
	nEWLINETokens := OrderedCollection new: 2.
	iNDENTTokens := OrderedCollection new: 2.
	dEDENTTokens := OrderedCollection new: 2.
	exceptTokens := OrderedCollection new: 2.
	excepts := OrderedCollection new: 2.
	asTokens := OrderedCollection new: 2.
	anothers := OrderedCollection new: 2.
	commaTokens := OrderedCollection new: 2.
	except2s := OrderedCollection new: 2.