generated
pluralVariablesMap
	^ Dictionary new
		at: 'colonToken' put: 'colonTokens';
		at: 'suite' put: 'suites';
		at: 'nEWLINEToken' put: 'nEWLINETokens';
		at: 'iNDENTToken' put: 'iNDENTTokens';
		at: 'dEDENTToken' put: 'dEDENTTokens';
		at: 'exceptToken' put: 'exceptTokens';
		at: 'except' put: 'excepts';
		at: 'asToken' put: 'asTokens';
		at: 'another' put: 'anothers';
		at: 'commaToken' put: 'commaTokens';
		at: 'except2' put: 'except2s';
		yourself