Class {
	#name : #ASTspecificationNodeVisitor,
	#superclass : #SmaCCParseNodeVisitor,
	#category : 'SmaCC-IDL'
}

{ #category : #generated }
ASTspecificationNodeVisitor >> visitAddExpr: anAddExpr [
	^ self visitspecification: anAddExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitAndExpr: anAndExpr [
	^ self visitspecification: anAndExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitAnyType: anAnyType [
	^ self visitspecification: anAnyType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitArrayDeclarator: anArrayDeclarator [
	^ self visitspecification: anArrayDeclarator
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitAttrDcl: anAttrDcl [
	^ self visitspecification: anAttrDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitBaseTypeSpec: aBaseTypeSpec [
	^ self visitspecification: aBaseTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitBooleanLiteral: aBooleanLiteral [
	^ self visitspecification: aBooleanLiteral
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitBooleanType: aBooleanType [
	^ self visitspecification: aBooleanType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitCase: aCase [
	^ self visitspecification: aCase
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitCaseLabel: aCaseLabel [
	^ self visitspecification: aCaseLabel
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitCaseLabels: aCaseLabels [
	^ self visitspecification: aCaseLabels
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitCharType: aCharType [
	^ self visitspecification: aCharType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitComplexDeclarator: aComplexDeclarator [
	^ self visitspecification: aComplexDeclarator
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitConstDcl: aConstDcl [
	^ self visitspecification: aConstDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitConstExp: aConstExp [
	^ self visitspecification: aConstExp
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitConstType: aConstType [
	^ self visitspecification: aConstType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitConstrTypeSpec: aConstrTypeSpec [
	^ self visitspecification: aConstrTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitContextExpr: aContextExpr [
	^ self visitspecification: aContextExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitDeclarator: aDeclarator [
	^ self visitspecification: aDeclarator
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitDeclarators: aDeclarators [
	^ self visitspecification: aDeclarators
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitDefinition: aDefinition [
	^ self visitspecification: aDefinition
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitDefinitions: aDefinitions [
	^ self visitspecification: aDefinitions
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitElementSpec: anElementSpec [
	^ self visitspecification: anElementSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitEnumType: anEnumType [
	^ self visitspecification: anEnumType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitEnumerator: anEnumerator [
	^ self visitspecification: anEnumerator
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitEnumerators: anEnumerators [
	^ self visitspecification: anEnumerators
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitExceptDcl: anExceptDcl [
	^ self visitspecification: anExceptDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitExport: anExport [
	^ self visitspecification: anExport
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitFixedArraySize: aFixedArraySize [
	^ self visitspecification: aFixedArraySize
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitFixedArraySizes: aFixedArraySizes [
	^ self visitspecification: aFixedArraySizes
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitFloatingPtType: aFloatingPtType [
	^ self visitspecification: aFloatingPtType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitForwardDcl: aForwardDcl [
	^ self visitspecification: aForwardDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitInheritanceSpec: anInheritanceSpec [
	^ self visitspecification: anInheritanceSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitIntegerType: anIntegerType [
	^ self visitspecification: anIntegerType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitInterface: anInterface [
	^ self visitspecification: anInterface
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitInterfaceBody: anInterfaceBody [
	^ self visitspecification: anInterfaceBody
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitInterfaceDcl: anInterfaceDcl [
	^ self visitspecification: anInterfaceDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitInterfaceHeader: anInterfaceHeader [
	^ self visitspecification: anInterfaceHeader
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitLiteral: aLiteral [
	^ self visitspecification: aLiteral
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitMember: aMember [
	^ self visitspecification: aMember
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitMemberList: aMemberList [
	^ self visitspecification: aMemberList
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitModule: aModule [
	^ self visitspecification: aModule
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitMultExpr: aMultExpr [
	^ self visitspecification: aMultExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitOctetType: anOctetType [
	^ self visitspecification: anOctetType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitOpAttribute: anOpAttribute [
	^ self visitspecification: anOpAttribute
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitOpDcl: anOpDcl [
	^ self visitspecification: anOpDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitOpDclOptions: anOpDclOptions [
	^ self visitspecification: anOpDclOptions
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitOpTypeSpec: anOpTypeSpec [
	^ self visitspecification: anOpTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitOrExpr: anOrExpr [
	^ self visitspecification: anOrExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitParamAttribute: aParamAttribute [
	^ self visitspecification: aParamAttribute
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitParamDcl: aParamDcl [
	^ self visitspecification: aParamDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitParamDcls: aParamDcls [
	^ self visitspecification: aParamDcls
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitParamTypeSpec: aParamTypeSpec [
	^ self visitspecification: aParamTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitParameterDcls: aParameterDcls [
	^ self visitspecification: aParameterDcls
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitPositiveIntConst: aPositiveIntConst [
	^ self visitspecification: aPositiveIntConst
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitPrimaryExpr: aPrimaryExpr [
	^ self visitspecification: aPrimaryExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitRaisesExpr: aRaisesExpr [
	^ self visitspecification: aRaisesExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitScopedName: aScopedName [
	^ self visitspecification: aScopedName
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitScopedNames: aScopedNames [
	^ self visitspecification: aScopedNames
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSequenceType: aSequenceType [
	^ self visitspecification: aSequenceType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitShiftExpr: aShiftExpr [
	^ self visitspecification: aShiftExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSignedInt: aSignedInt [
	^ self visitspecification: aSignedInt
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSignedLongInt: aSignedLongInt [
	^ self visitspecification: aSignedLongInt
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSignedShortInt: aSignedShortInt [
	^ self visitspecification: aSignedShortInt
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSimpleDeclarator: aSimpleDeclarator [
	^ self visitspecification: aSimpleDeclarator
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSimpleDeclarators: aSimpleDeclarators [
	^ self visitspecification: aSimpleDeclarators
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSimpleTypeSpec: aSimpleTypeSpec [
	^ self visitspecification: aSimpleTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSpecification: aSpecification [
	^ self visitspecification: aSpecification
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitStringLiterals: aStringLiterals [
	^ self visitspecification: aStringLiterals
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitStringType: aStringType [
	^ self visitspecification: aStringType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitStructType: aStructType [
	^ self visitspecification: aStructType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSwitchBody: aSwitchBody [
	^ self visitspecification: aSwitchBody
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitSwitchTypeSpec: aSwitchTypeSpec [
	^ self visitspecification: aSwitchTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitTemplateTypeSpec: aTemplateTypeSpec [
	^ self visitspecification: aTemplateTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitTypeDcl: aTypeDcl [
	^ self visitspecification: aTypeDcl
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitTypeDeclarator: aTypeDeclarator [
	^ self visitspecification: aTypeDeclarator
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitTypeSpec: aTypeSpec [
	^ self visitspecification: aTypeSpec
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitUnaryExpr: anUnaryExpr [
	^ self visitspecification: anUnaryExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitUnaryOperator: anUnaryOperator [
	^ self visitspecification: anUnaryOperator
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitUnionType: anUnionType [
	^ self visitspecification: anUnionType
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitUnsignedInt: anUnsignedInt [
	^ self visitspecification: anUnsignedInt
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitUnsignedLongInt: anUnsignedLongInt [
	^ self visitspecification: anUnsignedLongInt
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitUnsignedShortInt: anUnsignedShortInt [
	^ self visitspecification: anUnsignedShortInt
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitXorExpr: aXorExpr [
	^ self visitspecification: aXorExpr
]

{ #category : #generated }
ASTspecificationNodeVisitor >> visitspecification: aspecification [
	^ self visitSmaCCParseNode: aspecification
]
