generated-initialize-release
initialize
	super initialize.
	_attributes := OrderedCollection new: 2.
	newTokens := OrderedCollection new: 2.
	publicTokens := OrderedCollection new: 2.
	protectedTokens := OrderedCollection new: 2.
	internalTokens := OrderedCollection new: 2.
	privateTokens := OrderedCollection new: 2.
	staticTokens := OrderedCollection new: 2.
	readonlyTokens := OrderedCollection new: 2.
	volatileTokens := OrderedCollection new: 2.
	unsafeTokens := OrderedCollection new: 2.
	declarators := OrderedCollection new: 2.
	commaTokens := OrderedCollection new: 2.