generated
pluralVariablesMap
	^ [ 
	Dictionary new
		at: 'attribute' put: 'attributes';
		at: 'newToken' put: 'newTokens';
		at: 'publicToken' put: 'publicTokens';
		at: 'protectedToken' put: 'protectedTokens';
		at: 'internalToken' put: 'internalTokens';
		at: 'privateToken' put: 'privateTokens';
		at: 'staticToken' put: 'staticTokens';
		at: 'readonlyToken' put: 'readonlyTokens';
		at: 'volatileToken' put: 'volatileTokens';
		at: 'unsafeToken' put: 'unsafeTokens';
		at: 'declarator' put: 'declarators';
		at: 'commaToken' put: 'commaTokens';
		yourself ] once