generated-reduction actions
reduceActionFortuple_type_element_list2: nodes
	| result |
	result := nodes at: 3.
	self addAllFirst: ((nodes at: 1) at: 1) to: (result at: 1).
	self addAllFirst: ((nodes at: 1) at: 2) to: (result at: 2).
	self addAllFirst: ((nodes at: 1) at: 3) to: (result at: 3).
	self addAllFirst: ((nodes at: 1) at: 4) to: (result at: 4).
	self addAllFirst: ((nodes at: 1) at: 5) to: (result at: 5).
	self addAllFirst: ((nodes at: 1) at: 6) to: (result at: 6).
	self addAllFirst: ((nodes at: 1) at: 7) to: (result at: 7).
	self addAllFirst: ((nodes at: 1) at: 8) to: (result at: 8).
	self addAllFirst: ((nodes at: 1) at: 9) to: (result at: 9).
	self addAllFirst: ((nodes at: 1) at: 10) to: (result at: 10).
	self addAllFirst: ((nodes at: 1) at: 11) to: (result at: 11).
	self addAllFirst: ((nodes at: 1) at: 12) to: (result at: 12).
	self addAllFirst: ((nodes at: 1) at: 13) to: (result at: 13).
	self addAllFirst: ((nodes at: 1) at: 14) to: (result at: 14).
	self addAllFirst: ((nodes at: 1) at: 15) to: (result at: 15).
	self addAllFirst: ((nodes at: 1) at: 16) to: (result at: 16).
	self addAllFirst: ((nodes at: 1) at: 17) to: (result at: 17).
	self addAllFirst: ((nodes at: 1) at: 18) to: (result at: 18).
	self addAllFirst: ((nodes at: 1) at: 19) to: (result at: 19).
	self addAllFirst: ((nodes at: 1) at: 20) to: (result at: 20).
	self addAllFirst: ((nodes at: 1) at: 21) to: (result at: 21).
	self addAllFirst: ((nodes at: 1) at: 22) to: (result at: 22).
	self addAllFirst: ((nodes at: 1) at: 23) to: (result at: 23).
	self addAllFirst: ((nodes at: 1) at: 24) to: (result at: 24).
	self addFirst: (nodes at: 2) to: (result at: 20).
	^ result