generated
pluralVariablesMap
	^ Dictionary new
		at: 'lambdaToken' put: 'lambdaTokens';
		at: 'nameToken' put: 'nameTokens';
		at: 'lparenToken' put: 'lparenTokens';
		at: 'rparenToken' put: 'rparenTokens';
		at: 'commaToken' put: 'commaTokens';
		at: 'equalToken' put: 'equalTokens';
		at: 'notToken' put: 'notTokens';
		at: 'upArrowToken' put: 'upArrowTokens';
		at: 'orToken' put: 'orTokens';
		at: 'andToken' put: 'andTokens';
		at: 'lessThanToken' put: 'lessThanTokens';
		at: 'greaterThanToken' put: 'greaterThanTokens';
		at: 'equalEqualToken' put: 'equalEqualTokens';
		at: 'greaterThanEqualToken' put: 'greaterThanEqualTokens';
		at: 'lessThanEqualToken' put: 'lessThanEqualTokens';
		at: 'lessThanGreaterThanToken' put: 'lessThanGreaterThanTokens';
		at: 'bangEqualToken' put: 'bangEqualTokens';
		at: 'inToken' put: 'inTokens';
		at: 'isToken' put: 'isTokens';
		at: 'plusToken' put: 'plusTokens';
		at: 'minusToken' put: 'minusTokens';
		at: 'lessThanLessThanToken' put: 'lessThanLessThanTokens';
		at: 'greaterThanGreaterThanToken' put: 'greaterThanGreaterThanTokens';
		at: 'tildeToken' put: 'tildeTokens';
		at: 'timesToken' put: 'timesTokens';
		at: 'divideToken' put: 'divideTokens';
		at: 'percentToken' put: 'percentTokens';
		at: 'divideDivideToken' put: 'divideDivideTokens';
		at: 'ifToken' put: 'ifTokens';
		at: 'elseToken' put: 'elseTokens';
		at: 'colonToken' put: 'colonTokens';
		at: 'timesTimesToken' put: 'timesTimesTokens';
		at: 'yieldToken' put: 'yieldTokens';
		at: 'lbrackToken' put: 'lbrackTokens';
		at: 'rbrackToken' put: 'rbrackTokens';
		at: 'lcurlyToken' put: 'lcurlyTokens';
		at: 'rcurlyToken' put: 'rcurlyTokens';
		at: '_Token' put: '_Tokens';
		at: 'numberToken' put: 'numberTokens';
		at: 'stringToken' put: 'stringTokens';
		at: 'periodToken' put: 'periodTokens';
		at: 'forToken' put: 'forTokens';
		yourself