generated-initialize-release
initialize
	super initialize.
	trailers := OrderedCollection new: 2.
	ones := OrderedCollection new: 2.
	orTokens := OrderedCollection new: 2.
	twos := OrderedCollection new: 2.
	ifTokens := OrderedCollection new: 2.
	ifs := OrderedCollection new: 2.
	elseTokens := OrderedCollection new: 2.
	elses := OrderedCollection new: 2.
	lambdaTokens := OrderedCollection new: 2.
	argumentses := OrderedCollection new: 2.
	colonTokens := OrderedCollection new: 2.
	bodies := OrderedCollection new: 2.
	tests := OrderedCollection new: 2.
	commaTokens := OrderedCollection new: 2.
	equalTokens := OrderedCollection new: 2.
	yieldTokens := OrderedCollection new: 2.
	names := OrderedCollection new: 2.
	asTokens := OrderedCollection new: 2.
	renames := OrderedCollection new: 2.
	nameTokens := OrderedCollection new: 2.
	statements := OrderedCollection new: 2.