generated
initialize
	super initialize.
	fromTokens := OrderedCollection new: 2.
	types := OrderedCollection new: 2.
	identifierTokens := OrderedCollection new: 2.
	inTokens := OrderedCollection new: 2.
	lhses := OrderedCollection new: 2.
	operators := OrderedCollection new: 2.
	rhses := OrderedCollection new: 2.
	letTokens := OrderedCollection new: 2.
	equalTokens := OrderedCollection new: 2.
	whereTokens := OrderedCollection new: 2.
	joinTokens := OrderedCollection new: 2.
	onTokens := OrderedCollection new: 2.
	equalsTokens := OrderedCollection new: 2.
	intoTokens := OrderedCollection new: 2.
	orderbyTokens := OrderedCollection new: 2.
	ascendingTokens := OrderedCollection new: 2.
	descendingTokens := OrderedCollection new: 2.
	commaTokens := OrderedCollection new: 2.
	selectTokens := OrderedCollection new: 2.
	groupTokens := OrderedCollection new: 2.
	byTokens := OrderedCollection new: 2.