generated
pluralVariablesMap
	^ Dictionary new
		at: 'fromToken' put: 'fromTokens';
		at: 'type' put: 'types';
		at: 'identifierToken' put: 'identifierTokens';
		at: 'inToken' put: 'inTokens';
		at: 'lhs' put: 'lhses';
		at: 'operator' put: 'operators';
		at: 'rhs' put: 'rhses';
		at: 'letToken' put: 'letTokens';
		at: 'equalToken' put: 'equalTokens';
		at: 'whereToken' put: 'whereTokens';
		at: 'joinToken' put: 'joinTokens';
		at: 'onToken' put: 'onTokens';
		at: 'equalsToken' put: 'equalsTokens';
		at: 'intoToken' put: 'intoTokens';
		at: 'orderbyToken' put: 'orderbyTokens';
		at: 'ascendingToken' put: 'ascendingTokens';
		at: 'descendingToken' put: 'descendingTokens';
		at: 'commaToken' put: 'commaTokens';
		at: 'selectToken' put: 'selectTokens';
		at: 'groupToken' put: 'groupTokens';
		at: 'byToken' put: 'byTokens';
		at: '_leftParen' put: '_leftParens';
		at: '_rightParen' put: '_rightParens';
		yourself