generated
reduceTable
^#(
	#(14 0 #reduceActionForRules1:) 
	#(17 0 #nil) 
	#(16 1 #reduceActionForFile1:) 
	#(17 1 #reduceActionForComment2:) 
	#(23 0 #reduceActionForStartStringExpression1:) 
	#(14 2 #reduceActionForRules2:) 
	#(14 2 #reduceActionForRules4:) 
	#(14 2 #reduceActionForRules3:) 
	#(24 0 #reduceActionForStartSmalltalkExpression1:) 
	#(18 1 #reduceActionForMatch3:) 
	#(18 1 #reduceActionForMatch1:) 
	#(27 3 #reduceActionForParserClass1:) 
	#(26 3 #reduceActionForImport1:) 
	#(18 2 #reduceActionForMatch2:) 
	#(18 2 #reduceActionForMatch4:) 
	#(20 4 #reduceActionForRule1:) 
	#(19 1 #reduceActionForTransformation1:) 
	#(19 1 #reduceActionForTransformation2:) 
	#(21 3 #reduceActionForFile1:) 
	#(22 3 #reduceActionForFile1:)
	).
