generated
reduceTable
^#(
	#(22 0 #reduceActionForRewriteExpressions1:) 
	#(17 0 #reduceActionForSwitchStateToExpression1:) 
	#(16 0 #reduceActionForSwitchStateToCode1:) 
	#(12 1 #reduceActionForExpression1:) 
	#(10 1 #reduceActionForStringReplace1:) 
	#(11 1 #reduceActionForRewriteExpression3:) 
	#(22 2 #reduceActionForRewriteExpressions2:) 
	#(18 0 #nil) 
	#(15 0 #reduceActionForSwitchStateToDefault1:) 
	#(18 1 #reduceActionForRewriteExpression3:) 
	#(21 0 #nil) 
	#(19 1 #reduceActionForRewriteExpression3:) 
	#(21 1 #reduceActionForRewriteExpression3:) 
	#(23 2 #reduceActionForPrefixModifiers2:) 
	#(8 5 #reduceActionForCodeReplace1:) 
	#(23 4 #reduceActionForPrefixModifiers1:) 
	#(14 2 #reduceActionForPrefixModifiers2:) 
	#(9 7 #reduceActionForNodeReplace1:) 
	#(14 4 #reduceActionForPostfixModifiers1:)
	).
