generated
reduceTable
^#(
	#(13 0 #reduceActionForRewriteExpressions1:) 
	#(19 0 #reduceActionForSwitchStateToExpression1:) 
	#(8 0 #reduceActionForSwitchStateToCode1:) 
	#(11 1 #reduceActionForExpression1:) 
	#(9 1 #reduceActionForStringReplace1:) 
	#(20 1 #reduceActionForRewriteExpression1:) 
	#(13 2 #reduceActionForRewriteExpressions2:) 
	#(18 0 #nil) 
	#(15 0 #reduceActionForSwitchStateToDefault1:) 
	#(18 1 #reduceActionForRewriteExpression1:) 
	#(21 0 #nil) 
	#(16 1 #reduceActionForRewriteExpression1:) 
	#(21 1 #reduceActionForRewriteExpression1:) 
	#(22 2 #reduceActionForPrefixModifiers2:) 
	#(17 5 #reduceActionForCodeReplace1:) 
	#(22 4 #reduceActionForPrefixModifiers1:) 
	#(14 2 #reduceActionForPrefixModifiers2:) 
	#(12 7 #reduceActionForNodeReplace1:) 
	#(14 4 #reduceActionForPostfixModifiers1:)
	).
